// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV0PbUz0A5yZdL1ihe4kwrhO0dl14ibVI',
    appId: '1:692928202441:web:b13f3eade5d3984182ef18',
    messagingSenderId: '692928202441',
    projectId: 'scratch-14b85',
    authDomain: 'scratch-14b85.firebaseapp.com',
    storageBucket: 'scratch-14b85.firebasestorage.app',
    measurementId: 'G-FDQZJM37YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8A8mGANxk9_qZrHhKBWMSCaNApHZtsSE',
    appId: '1:692928202441:android:7c776a76c674bd5e82ef18',
    messagingSenderId: '692928202441',
    projectId: 'scratch-14b85',
    storageBucket: 'scratch-14b85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoWWFMr3J2JapuWQbSZUhPjLTJTsLEd-M',
    appId: '1:692928202441:ios:fb50f5bbbb66c8d182ef18',
    messagingSenderId: '692928202441',
    projectId: 'scratch-14b85',
    storageBucket: 'scratch-14b85.firebasestorage.app',
    iosBundleId: 'com.example.tuwaiqApp',
  );
}
